"""CSVs -> build/fig_*.pdf. No model evaluation here: everything plotted
was generated by scripts/make_results.py (rule: figures from processed
data, one provenance chain)."""

from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import seaborn as sns  # noqa: E402
from matplotlib.lines import Line2D  # noqa: E402

BASE = Path(__file__).resolve().parents[1]
DATA = BASE / "data" / "processed"
BUILD = BASE / "build"

sns.set_theme(style="white", context="paper", font_scale=1.15)

LAM_EDGES = [20, 30, 45, 60, 500]
Z_EDGES = [0.20, 0.35, 0.50, 0.65]


def fig_ratio_grid():
    rows = np.loadtxt(DATA / "ratio_profiles.csv", delimiter=",")
    fig, axs = plt.subplots(3, 4, figsize=(13, 9), sharex=True, sharey=True)
    for j in range(3):
        for i in range(4):
            m = (rows[:, 0] == i) & (rows[:, 1] == j)
            R, rat_m, sig, rat_mod = rows[m, 2], rows[m, 3], rows[m, 4], rows[m, 5]
            ax = axs[j, i]
            ax.fill_between(R, rat_m - sig, rat_m + sig, alpha=0.35,
                            color="#7fa8c9", label=r"mock ($1\sigma$)")
            ax.plot(R, rat_mod, "k-", lw=1.6, label=r"\texttt{SigmaPrj}"
                    if False else "SigmaPrj")
            ax.axvline(3.0, ls=":", color="gray", lw=0.8)
            ax.axhline(1.0, ls="--", color="gray", lw=0.8)
            ax.set_xscale("log")
            ax.set_ylim(0.95, 1.40)
            ax.text(0.04, 0.88, rf"$\lambda\in[{LAM_EDGES[i]},{LAM_EDGES[i+1]})$"
                    "\n" rf"$z\in[{Z_EDGES[j]:.2f},{Z_EDGES[j+1]:.2f})$",
                    transform=ax.transAxes, fontsize=8.5)
            if i == 0:
                ax.set_ylabel(r"$\langle\Sigma_{\rm tot}\rangle_\lambda/"
                              r"\langle\Sigma_{\rm tot}\rangle_{\rm RND}$")
            if j == 2:
                ax.set_xlabel(r"$R$ [$h^{-1}$cMpc]")
    axs[0, 0].legend(fontsize=8.5, frameon=False, loc="upper right")
    fig.tight_layout()
    fig.savefig(BUILD / "fig_ratio_grid.pdf")
    plt.close(fig)


def fig_paper6():
    """Reproduce Costanzi 2026 Fig. 6: <Sigma^prj>_sel/<Sigma^prj>_RND-sel
    (solid, mock band + model) and b_lambda-ob(R)/b_eff (dashed, model),
    one panel per lambda bin, z color-coded within each panel."""
    rows = np.loadtxt(DATA / "ratio_profiles.csv", delimiter=",")
    z_colors = ["tab:blue", "tab:orange", "tab:green"]
    fig, axs = plt.subplots(1, 4, figsize=(15, 4), sharex=True, sharey=True)
    for i in range(4):
        ax = axs[i]
        for j in range(3):
            m = (rows[:, 0] == i) & (rows[:, 1] == j)
            R, rat_m, sig, rat_mod = (rows[m, 2], rows[m, 3], rows[m, 4],
                                       rows[m, 5])
            bsel_beff = rows[m, 12]
            c = z_colors[j]
            ax.fill_between(R, rat_m - sig, rat_m + sig, color=c, alpha=0.25)
            ax.plot(R, rat_mod, "-", color=c, lw=1.6)
            ax.plot(R, bsel_beff, "--", color=c, lw=1.3)
        ax.axhline(1.0, ls=":", color="gray", lw=0.8)
        ax.set_xscale("log")
        ax.set_ylim(0.98, 1.62)
        ax.set_xlabel(r"$R$ [$h^{-1}$cMpc]")
        ax.text(0.5, 0.94, rf"${LAM_EDGES[i]}<\lambda<{LAM_EDGES[i+1]}$",
                transform=ax.transAxes, fontsize=9.5, ha="center", va="top")
    axs[0].set_ylabel(r"$\langle\Sigma^{\rm prj}\rangle_{\lambda^{\rm ob}"
                       r"{\rm -sel}}/\langle\Sigma^{\rm prj}\rangle_{\rm RND-sel}$")
    handles = [Line2D([0], [0], color=z_colors[j], lw=2,
                      label=rf"${Z_EDGES[j]:.2f}<z<{Z_EDGES[j+1]:.2f}$")
               for j in range(3)]
    axs[0].legend(handles=handles, fontsize=8, frameon=False, loc="upper left")
    fig.tight_layout()
    fig.savefig(BUILD / "fig_paper6.pdf")
    plt.close(fig)


def fig_one2one():
    """The mock's measured column against BOTH model channels.

    The mock stores one profile per halo: the projected mass in the slab
    with the target's own halo removed. It is compared against the model's
    total Sigma_tot = Sigma_bkg + Sigma^prj and against the correlated
    channel Sigma^prj alone. Which of the two it follows changes with
    radius, and that crossover is the point of the figure."""
    rows = np.loadtxt(DATA / "ratio_profiles.csv", delimiter=",")
    fig, axs = plt.subplots(
        6, 4, figsize=(13, 11.5), sharex=True,
        gridspec_kw={"height_ratios": [3, 1.1] * 3, "hspace": 0.06,
                     "wspace": 0.07})
    for j in range(3):
        for i in range(4):
            m = (rows[:, 0] == i) & (rows[:, 1] == j)
            R = rows[m, 2]
            mock, err = rows[m, 6], rows[m, 10]
            model_tot, model_cl = rows[m, 8], rows[m, 11]
            bkg = model_tot - model_cl          # constant sheet
            ax, axr = axs[2 * j, i], axs[2 * j + 1, i]

            ax.fill_between(R, mock - err, mock + err, alpha=0.8, lw=0,
                            color="#7fa8c9", label="mock")
            ax.loglog(R, model_tot, "k-", lw=1.4,
                      label=r"model $\Sigma_{\rm tot}$")
            ax.loglog(R, model_cl, ls="--", color="#8C1D40", lw=1.4,
                      label=r"model $\Sigma^{\rm prj}$")
            ax.loglog(R, bkg, ls=":", color="gray", lw=1.3,
                      label=r"model $\Sigma_{\rm bkg}$")

            axr.semilogx(R, model_tot / mock, "k-", lw=1.5)
            axr.semilogx(R, model_cl / mock, ls="--", color="#8C1D40", lw=1.5)
            axr.fill_between(R, 1.0 - err / mock, 1.0 + err / mock,
                             alpha=0.8, lw=0, color="#7fa8c9")
            axr.axhline(1.0, ls="--", color="gray", lw=0.8)
            for a in (ax, axr):
                a.axvline(3.0, ls=":", color="gray", lw=0.8)
            ax.set_ylim(3e11, 3.0e13)
            axr.set_ylim(0.0, 1.6)
            ax.text(0.04, 0.06,
                    rf"$\lambda\in[{LAM_EDGES[i]},{LAM_EDGES[i+1]})$"
                    "\n" rf"$z\in[{Z_EDGES[j]:.2f},{Z_EDGES[j+1]:.2f})$",
                    transform=ax.transAxes, fontsize=8.5)
            if i == 0:
                ax.set_ylabel(r"$\Sigma$ [$M_\odot\,\mathrm{cMpc}^{-2}$]")
                axr.set_ylabel("model / mock", fontsize=9)
            else:
                ax.tick_params(labelleft=False)
                axr.tick_params(labelleft=False)
            if j == 2:
                axr.set_xlabel(r"$R$ [$h^{-1}$cMpc]")
    handles, labels = axs[0, 0].get_legend_handles_labels()
    fig.legend(handles, labels, fontsize=9.5, frameon=False, ncol=4,
               loc="lower center", bbox_to_anchor=(0.5, 0.905))
    fig.savefig(BUILD / "fig_one2one.pdf", bbox_inches="tight")
    plt.close(fig)


def fig_absolute():
    R, mock, err, model = np.loadtxt(DATA / "absolute.csv",
                                     delimiter=",", unpack=True)
    m = np.arange(R.size) >= 4
    fig, (ax, axr) = plt.subplots(
        2, 1, figsize=(6.2, 6.4), sharex=True,
        gridspec_kw={"height_ratios": [3, 1.2], "hspace": 0.06})
    ax.fill_between(R[m], (mock - err)[m], (mock + err)[m], alpha=0.35,
                    color="#7fa8c9", label=r"mock ($1\sigma$)")
    ax.loglog(R[m], model[m], "k-", lw=1.8, label="SigmaPrj")
    ax.axvline(3.0, ls=":", color="gray", lw=0.8)
    ax.set_ylabel(r"$\langle\Sigma_{\rm tot}\rangle$ [$M_\odot\,\mathrm{cMpc}^{-2}$]")
    ax.legend(frameon=False)
    axr.semilogx(R[m], (model / mock)[m], "k-", lw=1.6)
    axr.axhline(1.0, ls="--", color="gray", lw=0.8)
    axr.axvline(3.0, ls=":", color="gray", lw=0.8)
    axr.set_ylim(0.8, 1.7)
    axr.set_ylabel("model/mock")
    axr.set_xlabel(r"$R$ [$h^{-1}$cMpc]")
    fig.tight_layout()
    fig.savefig(BUILD / "fig_absolute.pdf")
    plt.close(fig)


def fig_decomposition():
    R, rnd, cl, tot = np.loadtxt(DATA / "decomposition.csv",
                                 delimiter=",", unpack=True)
    H = 0.7  # axis in cMpc/h, matching the other figures
    fig, ax = plt.subplots(figsize=(6.2, 4.6))
    ax.loglog(R * H, tot, "k-", lw=2.0,
              label=r"$\Sigma_{\rm tot} = \Sigma_{\rm bkg} + \Sigma^{\rm prj}$")
    ax.loglog(R * H, rnd, ls="--", color="#b3661e", lw=1.8,
              label=r"$\Sigma_{\rm bkg}$ (background)")
    ax.loglog(R * H, cl, ls=":", color="#3f7361", lw=2.0,
              label=r"$\Sigma^{\rm prj}$ (correlated)")
    ax.set_xlabel(r"$R$ [$h^{-1}$cMpc]")
    ax.set_ylabel(r"$\Sigma$ [$M_\odot\,\mathrm{cMpc}^{-2}$]")
    ax.legend(frameon=False)
    fig.tight_layout()
    fig.savefig(BUILD / "fig_decomposition.pdf")
    plt.close(fig)


def fig_inner_study():
    rows = np.loadtxt(DATA / "inner_study.csv", delimiter=",")
    names = {0: "Y3 EMG kernel", 1: r"self kernel $\times$ prior",
             2: r"point $\Delta_{\rm RND}$", 3: "fitted to mock"}
    styles = {0: ("-", "#8C1D40"), 1: (":", "#666666"),
              2: ("--", "#1F4E79"), 3: ("-", "k")}
    fig, ax = plt.subplots(figsize=(6.6, 4.8))
    m0 = rows[:, 0] == 0
    R = rows[m0, 1]
    ax.fill_between(R, (rows[m0, 2] - rows[m0, 3]),
                    (rows[m0, 2] + rows[m0, 3]), alpha=0.35,
                    color="#7fa8c9", label=r"mock ($1\sigma$)")
    for v in (0, 1, 2, 3):
        m = rows[:, 0] == v
        ls, c = styles[v]
        ax.plot(rows[m, 1], rows[m, 4], ls=ls, color=c, lw=1.8,
                label=names[v])
    ax.set_xscale("log")
    ax.set_ylim(0.95, 2.2)
    ax.axvline(3.0, ls=":", color="gray", lw=0.8)
    ax.set_xlabel(r"$R$ [$h^{-1}$cMpc]")
    ax.set_ylabel(r"$\langle\Sigma_{\rm tot}\rangle_\lambda/"
                  r"\langle\Sigma_{\rm tot}\rangle_{\rm RND}$")
    ax.legend(fontsize=9, frameon=False)
    fig.tight_layout()
    fig.savefig(BUILD / "fig_inner_study.pdf")
    plt.close(fig)


def fig_area_overlap():
    rows = np.loadtxt(DATA / "area_overlap_check.csv", delimiter=",")
    r_ltr_values = sorted(set(rows[:, 0]))
    colors = {r_ltr_values[0]: "#8C1D40", r_ltr_values[1]: "#1F4E79",
             r_ltr_values[2]: "#4B644A"}
    fig, ax = plt.subplots(figsize=(6.6, 4.8))
    for r_ltr in r_ltr_values:
        m = rows[:, 0] == r_ltr
        c = colors[r_ltr]
        ax.plot(rows[m, 1], rows[m, 2], "--", color=c, lw=1.4,
                label=rf"$r_{{\rm ltr}}={r_ltr:.2g}$: area\_overlap")
        ax.plot(rows[m, 1], rows[m, 3], "-", color=c, lw=1.8,
                label=rf"$r_{{\rm ltr}}={r_ltr:.2g}$: true (NFW)")
    ax.axvline(1.0, ls=":", color="gray", lw=0.8)
    ax.set_xlabel(r"$s = \theta_{\rm sep}/\theta_{\rm ob}$")
    ax.set_ylabel(r"companion richness fraction landing in target aperture")
    ax.legend(fontsize=7.5, frameon=False, ncol=2)
    fig.tight_layout()
    fig.savefig(BUILD / "fig_area_overlap.pdf")
    plt.close(fig)


if __name__ == "__main__":
    BUILD.mkdir(exist_ok=True)
    fig_ratio_grid()
    fig_paper6()
    fig_one2one()
    fig_absolute()
    fig_decomposition()
    fig_inner_study()
    fig_area_overlap()
    print("wrote 7 figures to", BUILD)
