r"""Miscentered NFW profiles by table lookup -- the runtime path.

`clenspy` does not solve the miscentering integrals at evaluation time. It
interpolates the packaged dimensionless grid
``clenspy/data/nfw_miscentering.npz``, built offline by
``tools/make_miscentering_table.py`` from
`clenspy.selection.miscentering_kernel`.

The lookup is possible because the single-offset profiles are universal in
units of the scale radius. With :math:`\Sigma_0 = 2 r_s \rho_s`,
:math:`x = R/r_s` and :math:`x_{\rm mis} = R_{\rm mis}/r_s`,

.. math::
    \Sigma_{\rm mis}(R \mid R_{\rm mis}, M, c)
      = \Sigma_0 \, \hat\Sigma_{\rm mis}(x, x_{\rm mis}),
    \qquad
    \Delta\Sigma_{\rm mis} = \Sigma_0 \, \widehat{\Delta\Sigma}_{\rm mis}
      (x, x_{\rm mis}),

so mass, concentration and cosmology enter only the prefactor and one grid
serves every halo (docs/miscentering_math.md section 9.1).

NOTE: units follow `NfwProfile` -- lengths in Mpc, densities in
Msun/Mpc^3, and the returned surface densities in Msun/Mpc^2.

NOTE: **comoving vs physical is decided by the profile's** ``rho_ref``,
not by this table: the grid is dimensionless and the scale is
:math:`\Sigma_0 = 2 r_s \rho_s \propto \rho_{\rm def}^{1/3}\cdot\rho_{\rm
def}` through :math:`(r_s, \rho_s)`. A comoving
:math:`\bar\rho_m = \Omega_m \rho_{c,0}` gives comoving
:math:`\Sigma`; the physical :math:`\rho_{\rm crit}(z)` (the
``y3_cluster_cpp`` ``nfw_off_center`` convention) gives physical
:math:`\Sigma = (1+z)^2 \Sigma_{\rm com}`. That :math:`(1+z)^2` is the
classic silent factor when comparing the two pipelines.

NOTE: :math:`\widehat{\Delta\Sigma}_{\rm mis}` is **signed** and negative
for :math:`x_{\rm mis} \gtrsim x`. That lobe is physical and is what makes
the mean-field term cancel -- do not clamp it (section 7).

The table is stored on axes :math:`(\ln x_{\rm mis}, \ln q)` with
:math:`q = x/x_{\rm mis}`, because the cusp at :math:`x = x_{\rm mis}` then
lies along a grid line instead of cutting diagonally across the cells
(section 9.3).

It is generated by `cluster_toolkit` for :math:`x_{\rm mis} \ge 0.1` and by
`clenspy.selection.miscentering_kernel` below that, where ct's
:math:`\bar\Sigma - \Sigma` cancels badly enough to flip the sign
(section 9.4).

Only NFW is tabulated. Other profiles raise `MiscenteringTableError` rather
than silently falling back to quadrature.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path

import numpy as np
from scipy.interpolate import RegularGridInterpolator

from ..halo.nfw import NfwProfile

__all__ = [
    "MiscenteringTableError",
    "NfwMiscenteringTable",
    "load_nfw_miscentering_table",
    "require_tabulated_profile",
]

TABLE_PATH = Path(__file__).resolve().parents[1] / "data" / "nfw_miscentering.npz"


class MiscenteringTableError(NotImplementedError):
    """No miscentering table exists for the requested profile."""


def require_tabulated_profile(profile) -> None:
    """Raise unless ``profile`` is one the packaged table covers.

    `clenspy` evaluates miscentering by interpolation only, so a profile
    with no table has no runtime path. Einasto is the case in practice:
    its miscentered profile is not universal in a single shape parameter
    the way NFW's is -- it carries the index ``n`` as a third axis -- so
    the NFW grid cannot be reused and no Einasto grid has been generated.

    Parameters
    ----------
    profile : object
        The centred halo profile, e.g. `NfwProfile`.

    Raises
    ------
    MiscenteringTableError
        If no table covers ``profile``.
    """
    if isinstance(profile, NfwProfile):
        return
    name = type(profile).__name__
    raise MiscenteringTableError(
        f"no miscentering table for {name}; only NfwProfile is tabulated. "
        "clenspy evaluates miscentering by interpolating "
        "clenspy/data/nfw_miscentering.npz and does not solve the offset "
        "integrals at runtime, so there is no fallback. To add support, "
        "generate a table with tools/make_miscentering_table.py -- note an "
        "Einasto grid needs a third axis in the index n."
    )


@lru_cache(maxsize=1)
def load_nfw_miscentering_table() -> "NfwMiscenteringTable":
    """The packaged NFW table, read once and cached for the process."""
    return NfwMiscenteringTable(TABLE_PATH)


class NfwMiscenteringTable:
    r"""Interpolator over the dimensionless miscentered NFW grid.

    Parameters
    ----------
    path : str or Path, optional
        Location of the ``.npz``. Defaults to the packaged table.

    Attributes
    ----------
    x_mis_range, q_range, x_range : tuple of float
        Covered ranges. Out-of-range handling differs by edge -- clamp
        below, centred closed form above; see `_query`.
    """

    def __init__(self, path=TABLE_PATH) -> None:
        path = Path(path)
        if not path.is_file():
            raise MiscenteringTableError(
                f"miscentering table not found at {path}. Build it with "
                "`python tools/make_miscentering_table.py`."
            )
        with np.load(path) as data:
            self._ln_x_mis = data["ln_x_mis"]
            self._ln_q = data["ln_q"]
            sigma_hat = data["sigma_hat_mis"]
            ds_hat = data["ds_hat_mis"]
            self._x_range = tuple(float(v) for v in data["x_range"])
        grid = (self._ln_x_mis, self._ln_q)
        opts = dict(method="linear", bounds_error=False, fill_value=None)
        self._sigma = RegularGridInterpolator(grid, sigma_hat, **opts)
        self._ds = RegularGridInterpolator(grid, ds_hat, **opts)
        self.path = path

    @property
    def x_mis_range(self) -> tuple[float, float]:
        return (float(np.exp(self._ln_x_mis[0])), float(np.exp(self._ln_x_mis[-1])))

    @property
    def q_range(self) -> tuple[float, float]:
        return (float(np.exp(self._ln_q[0])), float(np.exp(self._ln_q[-1])))

    @property
    def x_range(self) -> tuple[float, float]:
        r"""Tabulated range in :math:`x = R / r_s`."""
        return self._x_range

    @staticmethod
    def _centred_sigma(x):
        r"""Centred :math:`\Sigma / \Sigma_0 = f(x)`."""
        return NfwProfile._fNfw(x)

    @staticmethod
    def _centred_ds(x):
        r"""Centred :math:`\Delta\Sigma / \Sigma_0 = \bar{g}(x) - f(x)`."""
        return NfwProfile._gbarNfw(x) - NfwProfile._fNfw(x)

    def _query(self, interp, centred, x, x_mis):
        r"""Lookup at (x, x_mis), with the three bounds handled differently.

        Below the table's smallest **x_mis**, evaluate the centred closed
        form: an offset :math:`\ll r_s` is indistinguishable from no
        offset. Clamping the axis instead while building
        :math:`q = x/x_{\rm mis}` from the *raw* offset shears the lookup
        off the grid diagonal -- for :math:`x_{\rm mis} \sim 10^{-4}` the
        interpolant lands :math:`\sim\!20\times` low. (Found by
        `clenspy.lensing.projection.SigmaPrj`, whose smallest
        :math:`\theta` nodes are exactly this limit.)

        Below the table's smallest x, clamp: the query sits deep inside the
        offset ring, where the miscentered profile is flat, so the edge
        value is the right constant.

        Above the table's largest x, evaluate the **centred** closed form
        instead. There :math:`R \gg R_{\rm mis}` and the offset is
        irrelevant -- the miscentered profile converges on the centred one
        as :math:`1/q^2`, so at the right edge the centred form is accurate
        to :math:`\sim\!10^{-6}` for small :math:`x_{\rm mis}` and
        :math:`\sim\!10^{-2}` for the largest. Clamping there would instead
        return a constant while the true profile keeps falling, which is
        unbounded error.

        Above the table's largest **x_mis**, use the far-field limit
        (valid for :math:`x \lesssim x_{\rm mis}`, which is the only way
        such a query arises: an aperture or ring much smaller than the
        offset): the ring average of the distant halo's surface density
        is its local value, :math:`\hat\Sigma_{\rm mis} \to
        \hat\Sigma_{\rm cen}(x_{\rm mis})`, and the aperture mean equals
        the local value to :math:`O((x/x_{\rm mis})^2)`, so
        :math:`\widehat{\Delta\Sigma}_{\rm mis} \to 0`. Clamping the axis
        instead evaluates the halo :math:`x_{\rm mis}^{\max}/x_{\rm mis}`
        times closer than it is.
        """
        x = np.atleast_1d(np.asarray(x, dtype=float))
        if np.log(x_mis) < self._ln_x_mis[0]:
            return centred(x)
        if np.log(x_mis) > self._ln_x_mis[-1]:
            if interp is self._sigma:
                far = float(self._centred_sigma(
                    np.atleast_1d(float(x_mis)))[0])
                return np.full(x.shape, far)
            return np.zeros(x.shape)
        x_lo, x_hi = self._x_range
        out = np.empty(x.shape, dtype=float)

        above = x > x_hi
        tabled = ~above
        if np.any(tabled):
            xt = np.maximum(x[tabled], x_lo)          # clamp the left bound
            ln_xm = min(np.log(x_mis), self._ln_x_mis[-1])
            ln_q = np.clip(np.log(xt / x_mis), self._ln_q[0], self._ln_q[-1])
            pts = np.stack([np.full_like(ln_q, ln_xm), ln_q], axis=-1)
            out[tabled] = interp(pts)
        if np.any(above):
            out[above] = centred(x[above])
        return out

    def sigma_hat(self, x, x_mis) -> np.ndarray:
        r""":math:`\hat\Sigma_{\rm mis} = \Sigma_{\rm mis}/\Sigma_0`."""
        if x_mis == 0.0:
            return self._centred_sigma(np.atleast_1d(np.asarray(x, dtype=float)))
        return self._query(self._sigma, self._centred_sigma, x, x_mis)

    def ds_hat(self, x, x_mis) -> np.ndarray:
        r""":math:`\widehat{\Delta\Sigma}_{\rm mis}`, signed (see the module)."""
        if x_mis == 0.0:
            return self._centred_ds(np.atleast_1d(np.asarray(x, dtype=float)))
        return self._query(self._ds, self._centred_ds, x, x_mis)

    # -- physical, for a given halo --------------------------------------

    @staticmethod
    def _scale(profile: NfwProfile) -> tuple[np.ndarray, np.ndarray]:
        r""":math:`(r_s, \Sigma_0 = 2 r_s\rho_s)` for ``profile``."""
        rs = np.asarray(profile.rs, dtype=float)
        return rs, 2.0 * rs * np.asarray(profile.rho_s, dtype=float)

    def sigma_mis(self, profile: NfwProfile, R, r_mis) -> np.ndarray:
        r"""Miscentered :math:`\Sigma_{\rm mis}(R \mid r_{\rm mis})` [Msun/Mpc^2]."""
        require_tabulated_profile(profile)
        rs, sigma0 = self._scale(profile)
        return sigma0 * self.sigma_hat(np.asarray(R, dtype=float) / rs, r_mis / rs)

    def deltasigma_mis(self, profile: NfwProfile, R, r_mis) -> np.ndarray:
        r"""Miscentered :math:`\Delta\Sigma_{\rm mis}` [Msun/Mpc^2], signed."""
        require_tabulated_profile(profile)
        rs, sigma0 = self._scale(profile)
        return sigma0 * self.ds_hat(np.asarray(R, dtype=float) / rs, r_mis / rs)

    def mean_sigma_mis(self, profile: NfwProfile, R, r_mis) -> np.ndarray:
        r"""Miscentered aperture mean :math:`\bar\Sigma_{\rm mis}(<R)`.

        :math:`\bar\Sigma_{\rm mis} = \Sigma_{\rm mis} + \Delta\Sigma_{\rm mis}`
        by definition, so it costs no extra table.
        """
        return (self.sigma_mis(profile, R, r_mis)
                + self.deltasigma_mis(profile, R, r_mis))

    def __repr__(self) -> str:
        return (f"NfwMiscenteringTable(x_mis={self.x_mis_range}, "
                f"q={self.q_range[0]:.1e}..{self.q_range[1]:.1e})")


if __name__ == "__main__":
    table = load_nfw_miscentering_table()
    print(table)
    nfw = NfwProfile(m200=1e14, c200=4.0)
    R = np.array([0.1, 0.3, 1.0, 3.0])
    print(f"r_s = {float(nfw.rs):.4f} Mpc")
    for r_mis in (0.0, 0.1, 0.5):
        ds = table.deltasigma_mis(nfw, R, r_mis)
        print(f"  r_mis={r_mis:.2f}  DeltaSigma_mis = "
              + "  ".join(f"{v:+.4e}" for v in np.ravel(ds)))
